### ISSUE TITLE
antiSMASH compatibility

### ISSUE THREAD

**Issue by lisizzz** [Finn-Lab/SanntiS#3]
I got a new problem when I ran the output JSON file together with the input FASTA file to antiSMASH. The message says the annotation is too long, but the annotation for the sanntis testfile is about the same length and ran successfully. I have attached the antiSMASH error message and the JSON file below.

<img width="1149" alt="Screenshot 2023-10-04 at 10 03 31" src="https://github.com/Finn-Lab/SanntiS/assets/118192474/b2b8b486-f4c0-4b5d-ac83-f5a15fd05641">
<img width="609" alt="Screenshot 2023-10-04 at 10 05 28" src="https://github.com/Finn-Lab/SanntiS/assets/118192474/338817d5-3cde-48ff-9f2d-4119974457ee">

**Comment by SantiagoSanchezF** [comment]
Hello @lisizzz ,

I appreciate your patience and feedback on this.

The problem you encountered was due to a limitation concerning the maximum string length for the "label" field. Under specific circumstances, our tool's output could exceed this limit, causing the error you've reported.

I've have fixed the error. The corrected version will soon be available on bioconda. However, to help you bypass this limitation, you can use the following code:

```python
import sys
import json

def correct_json(input_file, output_file):
    with open(input_file, 'r') as h:
        data = json.load(h)
    
    # Correcting the variable type
    for record in data['records']:
        for subregion in record['subregions']:
            subregion['details']["ID"] = subregion["label"]
            subregion['label'] = subregion['details']["class"][:20]
    
    with open(output_file, "w") as h:
        json.dump(data, h, indent=4)

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python script_name.py <input_file> <output_file>")
        sys.exit(1)

    input_file, output_file = sys.argv[1:3]
    correct_json(input_file, output_file)
```

Run the script by providing your old JSON file as input and specify where you'd like the corrected file to be saved.
Ensure you replace "script_name.py" with the actual name of the script if you decide to save it to a file.

``` sh
python script_name.py old_file.json corrected_file.json
```

This approach now stores BGCs ID on `subregion["details"]["ID"]`

Thank you for your feedback
Best
