### ISSUE TITLE
Empty output files

### ISSUE THREAD

**Issue by lisizzz** [Finn-Lab/SanntiS#5]
Hi,

Sanntis seems to run successfully, but the .gff file is empty.

A screenshot of the contents of the .gff file and the sanntis-log file is attached below.

<img width="569" alt="Screenshot 2023-12-11 at 12 24 01" src="https://github.com/Finn-Lab/SanntiS/assets/118192474/a72452c0-d260-41c8-9560-469227b43884">

[sanntis.log](https://github.com/Finn-Lab/SanntiS/files/13634705/sanntis.log)

**Comment by lisizzz** [comment]
The input fasta-file has the accession number: NC_017628.1, and it should contain 11 BGCs.

**Comment by SantiagoSanchezF** [comment]
Hi @lisizzz,

I ran SanntiS with the NC_017628.1 fasta (got it from NCBI's nucleotide db) and the resulting gff has the 11 BGCs you've mentioned.

A common issue is that the interproscan.sh is not available in the SanntiS environment.
Could you try to run interproscan by itself to check that its running ok?

Or could you provide the sanntis.log file to investigate this further?

**Comment by lisizzz** [comment]
Hi,

Thank you for your response.

I found it difficult to set up the SanntiS environment, so that is most likely where the error lies. 

After submitting the issue above, I made some modifications with my SanntiS environment. After I've done that I ran the test-files; the first one (sanntis --ip-file test/files/BGC0001472.fna.prodigal.faa.gff3 test/files/BGC0001472.fna.prodigal.faa.gb) executed successfully, but I got an error with the second (sanntis test/files/BGC0001472.fna). I have attached a screenshot of the error message and the “sanntis.log” below.

[sanntis.log](https://github.com/Finn-Lab/SanntiS/files/13649894/sanntis.log)

<img width="570" alt="Screenshot 2023-12-12 at 15 57 40" src="https://github.com/Finn-Lab/SanntiS/assets/118192474/13fd3e1a-ebec-4440-b5ca-401777b861e9">

Regarding the installation of InterProScan, should I install it as a conda package inside the SanntiS environment, or as a separate copy as described here: https://interproscan-docs.readthedocs.io/en/latest/HowToDownload.html, or as a combination of both (as I have done).

To install SanntiS and InterProScan, I followed these steps:
1. Installing InterProScan (https://interproscan-docs.readthedocs.io/en/latest/HowToDownload.html):
    - mkdir interproscan
    - cd interproscan
    - wget https://ftp.ebi.ac.uk/pub/software/unix/iprscan/5/5.65-97.0/interproscan-5.65-97.0-64-bit.tar.gz
    - wget https://ftp.ebi.ac.uk/pub/software/unix/iprscan/5/5.65-97.0/interproscan-5.65-97.0-64-bit.tar.gz.md5
    - md5sum -c interproscan-5.65-97.0-64-bit.tar.gz.md5
    - tar -pxvzf interproscan-5.65-97.0-*-bit.tar.gz
    - cd interproscan-5.65-97.0
    - python3 setup.py -f interproscan.properties
    - (Path to interproscan: /cluster/projects/nn9383k/lisi/interproscan/interproscan-5.65-97.0)
2. Creating SanntiS environment:
    - conda create -n sanntis sanntis
    - conda activate sanntis
    - conda install interproscan
    - (Path to sanntis environment: /cluster/projects/nn9383k/lisi/miniconda3/envs/sanntis)
3. Connecting InterProScan to Sanntis (these lines of code were added after the initial issue submission):
    - rm -rf /cluster/projects/nn9383k/lisi/miniconda3/envs/sanntis/share/InterProScan/data/
    - cp -r /cluster/projects/nn9383k/lisi/interproscan/interproscan-5.65-97.0/data /cluster/projects/nn9383k/lisi/miniconda3/envs/sanntis/share/InterProScan/

If the steps above are wrong, could you please provide a detailed description of the installation steps?

**Comment by SantiagoSanchezF** [comment]
Hi @lisizzz,

`sanntis --ip-file test/files/BGC0001472.fna.prodigal.faa.gff3 test/files/BGC0001472.fna.prodigal.faa.gb)` works because you are providing the preprocessed InterProScan file.
`sanntis test/files/BGC0001472.fna) ` because InterProScan seems to be have an issue with the DB. I know this because `Error: File existence/permissions problem in trying to open HMM file data/tigrfam/15.0/TIGRFAMs_HMM.LIB` in the sanntis.log file

I would suggest some modifications to your installations steps:

1. Installing InterProScan (https://interproscan-docs.readthedocs.io/en/latest/HowToDownload.html):
- mkdir interproscan
- cd interproscan
- wget https://ftp.ebi.ac.uk/pub/software/unix/iprscan/5/5.65-97.0/interproscan-5.65-97.0-64-bit.tar.gz
- wget https://ftp.ebi.ac.uk/pub/software/unix/iprscan/5/5.65-97.0/interproscan-5.65-97.0-64-bit.tar.gz.md5
- md5sum -c interproscan-5.65-97.0-64-bit.tar.gz.md5
- tar -pxvzf interproscan-5.65-97.0-*-bit.tar.gz
- cd interproscan-5.65-97.0
- python3 setup.py -f interproscan.properties
- `interproscan.sh -help` to make sure that installation is ok
- (Path to interproscan: /cluster/projects/nn9383k/lisi/interproscan/interproscan-5.65-97.0)

2. Creating SanntiS environment: (don't `conda install interproscan `)
- cd $HOME (to make sure not in the IPS directory)
- conda create -n sanntis sanntis
- conda activate sanntis
- interproscan.sh -help (to make sure that the script is in path)
- if the above does not work, try `export PATH=<Path to interproscan>:$PATH ` . Then retry `interproscan.sh -help`
- add the `export PATH...` to $HOME/.bashrc for persistance

I think this should work.
Let me know if you any more questions.

**Comment by lisizzz** [comment]
Hi again,

Thank you so much. I deleted everything and follwed the installation steps as you described. After executing "export PATH ...", everything now works!

However, I need to move the SanntiS environment to a server that doesn't have an internett connection. I used conda-pack to import the installed SanntiS environment to the server, and I also imported the .tar.gz and .tar.gz.md5 files. I did the rest of the steps as you said. 

"interproscan.sh -help" works. 
"sanntis --ip-file test/files/BGC0001472.fna.prodigal.faa.gff3 test/files/BGC0001472.fna.prodigal.faa.gb" also works. 
But "sanntis test/files/BGC0001472.fna", didn't work. A screenshot of the error message follows below.

<img width="723" alt="Screenshot 2023-12-13 at 18 19 07" src="https://github.com/Finn-Lab/SanntiS/assets/118192474/6b89e1e1-542e-464c-b048-b30af7535d06">

The server contains sensitive data, so I'm not allowed to export the "sanntis.log", but I tok a screenshot of where I think the error is.

<img width="1030" alt="Screenshot 2023-12-13 at 18 29 13" src="https://github.com/Finn-Lab/SanntiS/assets/118192474/ad03a297-fe3e-4cc1-ae96-9d064f8cb957">

**Comment by SantiagoSanchezF** [comment]
Hi @lisizzz,

I'm glad to hear that you were able to successfully set up the sanntis environment and is working as expected. However, I understand that you are encountering an issue with the specific installation of interproscan, which is failing to produce an interproscan output file, and therefore propagating the error to sanntis.

The error message you provided indicates a problem with the GLIBC version:
`bin/prosite/pfscanV3: /lib64/libm.so.6: version GLIBC_2.27' not found (required by bin/prosite/pfscanV3)`

This error suggests that the GLIBC version required by a binary is not available on the system. Since you are moving the environment to a server, it's possible that the versions of the local and server libraries are not matching.

I suggest to try the following:
- Make sure to have the same GLIBC_2.27 version on both machines at the time of running `python3 setup.py -f interproscan.properties `
- If possible, consider using Docker to containerize your SanntiS environment along with all its dependencies. Docker containers can be easily moved between machines, ensuring consistent environments. In the SanntiS repo, you can find a docker folder containing scripts and files that can be useful.

Please note that the specific steps to implement these solutions may depend on your server's configuration and other specifics.

Let us know if you have any further questions.
Best,

Santiago
