### ISSUE TITLE
CPU limits not working

### ISSUE THREAD

**Issue by lam-c** [Finn-Lab/SanntiS#6]
Hello, developer. I ran SanntiS with singularity image, and found that Sanntis flooding CPU regardless the param `--cpu 4` set in executed command.

I checked the log file (as below), it seemed like that hmm working as expected, restricting to 4 cpus. According to the duration of exceeding cpu quota and [this thread](https://github.com/tensorflow/tensorflow/issues/34415), I suspect the problem originating from `tensorflow.keras` when predict  BGC probability. Is there any chance to reduce CPU usage here, in align with the CPU number setting in sanntis command line?

It would be great if this problem could be resolved, and thank you for your time.

---

Working Environment:

- System info: `Linux version 4.18.0-372.19.1.el8_6.x86_64`
- Singularity image: `quay.io/microbiome-informatics/sanntis:0.9.3.2` (cannot limit CPU when create container due to linux cgroups v1)
- Command line: `sanntis --cpu 4 --ip-file InterProScan.tsv --outfile sanntis.gff   prokka.gbk`
- Log file of sanntis: 
[sanntis.log](https://github.com/Finn-Lab/SanntiS/files/13898114/sanntis.log)

**Comment by SantiagoSanchezF** [comment]
Hello,

Thank you for bringing this issue to our attention and for the detailed information you've provided. Your effort in diagnosing the problem is greatly appreciated.

We will look into how we can limit the CPU usage of TensorFlow. However, due to current workload and the issues noted in the thread you've quoted, it might take some time before we can provide a fix or a workaround.

In the meantime, if your setup allows, you might try running SanntiS in an environment where you can manually limit the CPU usage at the system level, as a temporary measure.

Thanks,
Santiago.

**Comment by lam-c** [comment]
Hi,

Thank you for considering this issue and providing solutions. 😉 

Best
